"""empty message

Revision ID: 8632b9ef1592
Revises: fe73b878c38a
Create Date: 2023-05-10 21:47:07.592564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8632b9ef1592'
down_revision = 'fe73b878c38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_url', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
