"""empty message

Revision ID: fe73b878c38a
Revises: 
Create Date: 2023-05-10 21:46:13.147693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe73b878c38a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=255), nullable=False),
    sa.Column('long_url', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('long_url'),
    sa.UniqueConstraint('short_code'),
    sa.UniqueConstraint('short_url')
    )
    op.create_table('bot_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_url')
    op.drop_table('url')
    # ### end Alembic commands ###
